---
- name: Ensure key packages are installed
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install essential packages
      apt:
        name:
          - vim
          - git
          - curl
          - wget
          - net-tools
        state: present

    - name: Install Python and pip
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Ensure pip is up to date
      pip:
        name: pip
        state: latest
        executable: pip3

    - name: Install Python packages
      pip:
        name:
          - virtualenv
          - numpy
          - pandas
        state: present
        executable: pip3

    - name: Install Docker
      apt:
        name: docker.io
        state: present
- name: Install ROS Noetic on Ubuntu
  hosts: all
  become: yes

  tasks:
    - name: Ensure required Ubuntu repositories are enabled
      apt_repository:
        repo: "deb http://archive.ubuntu.com/ubuntu {{ item }} main restricted universe multiverse"
        state: present
      loop:
        - focal
        - focal-updates
        - focal-security

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Add ROS GPG key
      apt_key:
        url: https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc
        state: present

    - name: Add ROS repository to sources list
      apt_repository:
        repo: "deb http://packages.ros.org/ros/ubuntu {{ ansible_distribution_release | lower }} main"
        state: present

    - name: Update apt cache after adding ROS repository
      apt:
        update_cache: yes

    - name: Install ROS Noetic Desktop-Full
      apt:
        name: ros-noetic-desktop-full
        state: present

    - name: Install additional ROS dependencies
      apt:
        name:
          - python3-rosdep
          - python3-rosinstall
          - python3-rosinstall-generator
          - python3-wstool
          - build-essential
        state: present

    - name: Initialize rosdep
      command: rosdep init
      args:
        creates: /etc/ros/rosdep/sources.list.d/20-default.list

    - name: Update rosdep
      command: rosdep update

    - name: Source ROS setup.bash in bashrc
      lineinfile:
        path: ~/.bashrc
        line: "source /opt/ros/noetic/setup.bash"
        state: present

    - name: Source ROS setup.bash for current session
      shell: source /opt/ros/noetic/setup.bash
      args:
        executable: /bin/bash

    - name: Install VNC
      apt:
        name:
          - tigervnc-standalone-server
        state: present
